export const reviewsSummary = {
    rating: 5.0,
    starsCount: 5,
    reviewsCount: 80,
}

export const topReviews = [
    {
        id: 1,
        name: "Alex Johnson",
        review: "Outstanding service from start to finish! The inspector was incredibly thorough and professional. They took their time examining every aspect of the vehicle, from the engine to the undercarriage. The detailed report helped me make an informed decision, and I felt confident throughout the entire process. Highly recommend their services!",
        rating: 5,
        avatarSrc: "/avatars/avatar-1.svg",
    },
    {
        id: 2,
        name: "Sarah Martinez",
        review: "Excellent pre-purchase inspection service! The inspector was punctual, knowledgeable, and very thorough. They explained everything clearly and provided a comprehensive report that saved me from making a costly mistake. Great value for money!",
        rating: 5,
        avatarSrc: "/avatars/avatar-2.svg",
    },
    {
        id: 3,
        name: "Michael Chen",
        review: "I'm so glad I chose this inspection service before buying my used car. The inspector was extremely professional and caught several issues that weren't visible to the untrained eye. The report was detailed and easy to understand. This service gave me peace of mind and saved me thousands!",
        rating: 5,
        avatarSrc: "/avatars/avatar-3.svg",
    },
    {
        id: 4,
        name: "Emma Wilson",
        review: "Fantastic experience! The inspector was very accommodating with scheduling and met me at the seller's location. They were thorough, professional, and took the time to explain their findings. The inspection report was comprehensive and helped me negotiate a better price. Definitely recommend!",
        rating: 5,
        avatarSrc: "/avatars/avatar-4.svg",
    },
    {
        id: 5,
        name: "David Thompson",
        review: "Amazing service! The inspector was incredibly detailed and professional. They checked everything from the engine to the paint work and provided valuable insights about the vehicle's condition. The report was delivered quickly and was very comprehensive. Worth every penny!",
        rating: 5,
        avatarSrc: "/avatars/avatar-5.svg",
    },
    {
        id: 6,
        name: "Lisa Rodriguez",
        review: "I've used this inspection service multiple times now, and they never disappoint. The inspector is always thorough, professional, and honest. Their expertise has helped me make informed decisions on several vehicle purchases. The rates are reasonable and the service is exceptional!",
        rating: 5,
        avatarSrc: "/avatars/avatar-6.svg",
    },
    {
        id: 7,
        name: "James Anderson",
        review: "Top-notch inspection service! The inspector was knowledgeable, thorough, and provided excellent communication throughout the process. The detailed report highlighted both positive aspects and potential concerns, which was exactly what I needed to make my decision. Highly recommended!",
        rating: 5,
        avatarSrc: "/avatars/avatar-7.svg",
    },
    {
        id: 8,
        name: "Rachel Kim",
        review: "Exceptional service! The inspector took their time to thoroughly examine the vehicle and explained everything in terms I could understand. The comprehensive report gave me confidence in my purchase decision. Professional, reliable, and definitely worth the investment!",
        rating: 5,
        avatarSrc: "/avatars/avatar-8.svg",
    },
    {
        id: 9,
        name: "Robert Brown",
        review: "Outstanding inspection service! The inspector was professional, detailed, and honest throughout the entire process. They even took the car for a test drive and checked under the hood thoroughly. The seller was impressed with their professionalism. Couldn't be happier with the service!",
        rating: 5,
        avatarSrc: "/avatars/avatar-9.svg",
    },
    {
        id: 10,
        name: "Jennifer Davis",
        review: "HIGHLY RECOMMEND! The inspector went above and beyond my expectations. They were flexible with scheduling, extremely thorough with the inspection, and provided exceptional customer service. When I needed a second inspection at short notice, they accommodated without hesitation. Outstanding service!",
        rating: 5,
        avatarSrc: "/avatars/avatar-10.svg",
    },
    {
        id: 11,
        name: "Kevin Miller",
        review: "Impressed with the quick response time and flexibility! The inspector managed to fit me in on short notice and even adjusted to a change in location. They were efficient, thorough, and provided all the information I needed to negotiate a better price. Will definitely use again!",
        rating: 5,
        avatarSrc: "/avatars/avatar-11.svg",
    },
    {
        id: 12,
        name: "Amanda Taylor",
        review: "Contacted them on Friday evening and had the inspection completed by Saturday afternoon - incredibly responsive! The report was detailed and thorough, covering everything I needed to know. Their analysis helped me save money on the purchase. Highly recommend this service!",
        rating: 5,
        avatarSrc: "/avatars/avatar-12.svg",
    },
    {
        id: 13,
        name: "Christopher Lee",
        review: "Extremely professional service! The inspector provided a detailed assessment and comprehensive report before my purchase. They were willing to travel a considerable distance to meet at the seller's location, which I greatly appreciated. Excellent service for pre-purchase inspections!",
        rating: 5,
        avatarSrc: "/avatars/avatar-13.svg",
    },
    {
        id: 14,
        name: "Nicole Garcia",
        review: "Amazing turnaround time! The inspector completed a comprehensive pre-purchase inspection within hours of my initial call. They were genuine, professional, and maintained excellent communication throughout the process. Highly recommend their services!",
        rating: 5,
        avatarSrc: "/avatars/avatar-14.svg",
    },
    {
        id: 15,
        name: "Daniel White",
        review: "Had an outstanding experience with this inspection service! The inspector was incredibly patient, friendly, and helpful from start to finish. They took time to explain everything clearly and conducted a very thorough examination. It was a smooth and professional experience. Highly recommend!",
        rating: 5,
        avatarSrc: "/avatars/avatar-15.svg",
    },
    {
        id: 16,
        name: "Michelle Turner",
        review: "Can't recommend this service highly enough! The inspector went above and beyond to assist me, providing exceptional service throughout. I'll definitely be using their services again and will consistently recommend them to anyone needing reliable and thorough vehicle inspections!",
        rating: 5,
        avatarSrc: "/avatars/avatar-16.svg",
    },
    {
        id: 17,
        name: "Andrew Clark",
        review: "Excellent service! The inspector arranged to meet directly at the dealership and completed a thorough inspection that was more detailed than any other company I've used. Great communication and solid advice throughout the process. Would definitely recommend for any pre-purchase inspection needs!",
        rating: 5,
        avatarSrc: "/avatars/avatar-17.svg",
    },
    {
        id: 18,
        name: "Stephanie Hall",
        review: "Fantastic service! The inspector was pleasant, professional, and punctual. The report was extremely thorough and detailed, catching even minor issues that could become problems later. They delivered exactly what was promised. Excellent value and service!",
        rating: 5,
        avatarSrc: "/avatars/avatar-18.svg",
    },
    {
        id: 19,
        name: "Tyler Martinez",
        review: "Extremely satisfied with the service! The inspector is incredibly responsive and accommodated my last-minute request for a same-day inspection. They have excellent attention to detail, provide quick updates, and deliver comprehensive reports. Outstanding follow-up service too!",
        rating: 5,
        avatarSrc: "/avatars/avatar-1.svg",
    },
    {
        id: 20,
        name: "Jessica Adams",
        review: "Outstanding customer service! The inspector took sufficient time to thoroughly examine the vehicle with professional equipment and was very punctual. The money spent on this pre-purchase inspection was absolutely worth it. Highly recommended service!",
        rating: 5,
        avatarSrc: "/avatars/avatar-2.svg",
    },
]
